# fly.toml app configuration file generated for thee-kitchen on 2026-02-23T16:50:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thee-kitchen'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  FLASK_ENV = 'production'
  PORT = '8080'

[processes]
  app = 'gunicorn --bind 0.0.0.0:8080 app:app'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  processes = ['app']

[checks]
  [checks.alive]
    type = 'tcp'
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
